### ISSUE TITLE
packages released with potentially incorrect path

### ISSUE THREAD

**Issue by mcwarman** [updatecli/policies#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looking at the packages there's a double `policies`:

```shell
docker pull ghcr.io/updatecli/policies/policies/nodejs/githubaction:0.4.0
```

https://github.com/orgs/updatecli/packages?repo_name=policies

### Expected Behavior

```shell
docker pull ghcr.io/updatecli/policies/nodejs/githubaction:0.4.0
```

**Comment by olblak** [comment]
Thanks for the feedback, this is something that bother me as well, and reading you comment makes me realize that it's better to drop the second "policies"

The fix should be easily done [here](https://github.com/updatecli/policies/blob/84e29303e15284071f61cf26bcfd62568ef69eea/.ci/scripts/release.bash#L23C12-L23C16)

Basically `updatecli/policies` represents the git repository name and I decided to add the "policies" to highlight that it wasn't  a regular docker image like `ghcr.io/updatecli/updatecli`

Also something to keep in mind is for leveraging jsonschema for `Policy.yaml` I need it to be under `updatecli/**/Policy.yaml` as explained on https://github.com/SchemaStore/schemastore/pull/3325 hence the path structure
